source 'https://github.com/fyhNB/PGPodRepo.git'

use_frameworks!

platform :ios, '13.0'

target 'Router_Example' do
  pod 'Router', :path => '../'

  target 'Router_Tests' do
    inherit! :search_paths

    
  end
end
